function [dxdt] = air(t,x,p)

dxdt = [x(2);...
    -p.g-(p.k_leg)/p.m_leg*(x(1)-p.L_leg-x(3))-(p.c_leg*(x(2)-x(4))/p.m_leg);...
    x(4);...
    -p.g+(p.k_leg)/p.m_foot*(x(1)-p.L_leg-x(3))+(p.c_leg*(x(2)-x(4))/p.m_foot)]; 

end